# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
    steps:
    - uses: actions/checkout@v2
    - name: Starting Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install modules
      run: npm install
      if: always()
    - name: build production
      run: npm run build:prod
      if: always()
    - name: lint ts
      run: npm run lint:ts
      if: always()
    - name: lint scss
      run: npm run lint:scss
      if: always()
    - name: unit testing
      run: npm run test:unit
      if: always()
    - name: story build
      run: npm run build:storybook
      if: always()
    - name: screenshot testing
      run: npm run test:ui:ci
